# render.yaml
services:
  # Servicio principal de la API
  - type: web
    name: photo-picker-api
    env: python
    region: ohio
    plan: free
    branch: main
    
    # Comandos de construcción
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p uploads thumbnails
    
    # Comando de inicio
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300
    
    # Variables de entorno
    envVars:
      - key: DB_HOST
        value: 20.84.99.214
      - key: DB_PORT
        value: 443
      - key: DB_NAME
        value: PhotoPickerAPI
      - key: DB_USER
        value: photopicker_user
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: UPLOAD_DIR
        value: uploads
      - key: THUMBNAIL_DIR
        value: thumbnails
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PGSSLMODE
        value: disable
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
    
    # Health check path
    healthCheckPath: /health
    
    # Configuración de disco (necesario para almacenar archivos)
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

    autoDeploy: true

# Solo necesitas configurar el secret DB_PASSWORD en el dashboard de Render