# render.yaml
services:
  # Servicio principal de la API
  - type: web
    name: photo-picker-api
    env: python
    region: ohio  # Puedes cambiar a us-east, us-west, etc.
    plan: free  # O upgrade to starter, standard, etc.
    branch: main
    
    # Comandos de construcción
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    
    # Comando de inicio
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300
    
    # Variables de entorno
    envVars:
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_PORT
        fromSecret: DB_PORT
      - key: DB_NAME
        fromSecret: DB_NAME
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: UPLOAD_DIR
        value: uploads
      - key: THUMBNAIL_DIR
        value: thumbnails
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PGSSLMODE
        value: require
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
    
    # Health check path
    healthCheckPath: /health
    
    # Configuración de disco (necesario para almacenar archivos)
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

    # Auto-deploy configuration
    autoDeploy: true

# Secrets que necesitas configurar en el dashboard de Render
# DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD